public static class SplashText
{
    public static string[] Splashtext = {
        "Hotline Miami is the best game ever made..",
        "Hello world",
        "Hai :>",
        "(^///^)",
        "Can you expect better from me?",
        "Warframe is the best game ever made..",
        "Minecraft was the best game ever made..",
        "Cubed.init()",
        "Do you remember in the arcade build where somebody thought this was a trojan? Good times..",
        "I just drive..",
        "This game needs a hero?",
        "Nice desktop?",
        "Very cool Ed boy.",
        "So there's this one dude right named.. I dunno, I forgot already.. ",
        "I exist in many places at once..",
        "I know who you are.",
        "(!text) ? \"Am out of things to write\" : \"Place Flavor Text here!\"",
        "Very cool, didn't read. ",
        "I stole this idea from somebody..",
        "UwU",
        "This game needs some splash text.",
        "Everything by Everyone.",
        "They said I worshiped some dude named.. Stan?",
        "Written in Cobol",
        "Written in Haskell",
        "Actually written in C#",
        "Try Godot, note to self.",
        "Webfishing is cool.",
        "Nice try diddy",
        "Xiaohongshu",
        "With many thanks to, Lawrence Reed",
        "With many thanks to, Bhavik Chand",
        "With many thanks to, Kyle Lynn",
        "With many thanks to, Professor G",
        "Bears.. ",
        "Bnuny.. ",
        "They feel no pain, they died a million deaths.",
        "Linux support out of the box.",
        "Windows support out of the box.",
        "Mac support out of the box.",
        "Made in Unity.",
        "Hey guys, I guess thats it..",
        "So I can write anything here?",
        "So is Timetaker still in development?",
        "So is Cubed Phi still in development?",
        "So is Cubed still in development?",
        "Cubed Twah~",
        "Remember when I used to beat your ass over the creamed corn?",
        "No tweakers!",
        "We want you to be the cube..",
        "Your diggin in me!",
        "I couldn't even code to this, I seg faulted immediately! Clean up aisle my codebase!",
        "Thug hunteru no booru!",
        "We love lain..",
        "We love newgrounds..",
        "We like the yap sheesh.",
        "Your not on the hi list!",
        "Its the Party of your lifetime.",
        "Under the neon glow..",
        "This obsession has turned, Into the great despair.",
        "NaN", 
        "GR8 D2P@1R",
    };
    public static string GetSplashText() => Splashtext[UnityEngine.Random.Range(0, Splashtext.Length)];
    public static string GetCurrentSplash() => CurrentSplash;
    public static string CurrentSplash = Splashtext[UnityEngine.Random.Range(0, Splashtext.Length)];
}
