public static class SplashText
{
    // These are the splash texts that will be displayed on the main menu screen.
    // They are randomly selected from this list when the game starts.
    // Most of these are just gags or references to other games.
    // In lore, these are just nonsense messages that are displayed on the screen.
    public static string[] Splashtext = {
        "Hotline Miami is the best game ever made..",
        "Hello world",
        "These messages are not real.",
        "These messages are real.",
        "These messages are not real, but they are real.",
        "These messages are real, but they are not real.",
        "These messages are real, but they are not real, but they are real.",
        "These messages are not cannon.",
        "These messages are cannon.",
        "These messages are not cannon, but they are cannon.",
        "Nope not cannon.",
        "☆*: .｡. o(≧▽≦)o .｡.:*☆",
        "Hai :>",
        "(^///^)",
        "Can you expect better from me?",
        "Warframe is the best game ever made..",
        "Minecraft was the best game ever made..",
        "Cubed.init()",
        "Do you remember in the arcade build where somebody thought this was a trojan? Good times..",
        "I just drive..",
        "This game needs a hero?",
        "Nice desktop?",
        "Very cool Ed boy.",
        "So there's this one dude right named.. I dunno, I forgot already.. ",
        "I exist in many places at once..",
        "I know who you are.",
        "(!text) ? \"Am out of things to write\" : \"Place Flavor Text here!\"",
        "Very cool, didn't read. ",
        "I stole this idea from somebody..",
        "UwU",
        "This game needs some splash text.",
        "Everything by Everyone.",
        "They said I worshiped some dude named.. Stan?",
        "Written in Cobol",
        "Written in Haskell",
        "Actually written in C#",
        "Try Godot, note to self.",
        "Webfishing is cool.",
        "Xiaohongshu",
        "With many thanks to, Lawrence Reed",
        "With many thanks to, Bhavik Chand",
        "With many thanks to, Avner Biblarz",
        "With many thanks to, Chelle Tran",
        "With many thanks to, Professor G",
        "Bears.. ",
        "Bnuny.. ",
        "Dead rabbit..",
        "Fiver did not make the the cut.",  
        "Featuring, Richard Nixon",
        "Featuring, Ronnie McNutt",
        "Featuring, another dead rabbit",
        "Featuring, the guy from that one meme",
        "Featuring, the guy from that one meme, but with a different name",
        "Play Mindwave!",
        "Although the sky, might be gray~!",
        "They feel no pain, they died a million deaths.",
        "Linux support out of the box.",
        "Windows support out of the box.",
        "Mac support out of the box.",
        "Made in Unity.",
        "Hey guys, I guess thats it..",
        "<3",
        "Is it wrong to name my squrrel ronnie mcnutt?",
        "So I can write anything here?",
        "So is Timetaker still in development?",
        "So is Cubed Phi still in development?",
        "So is Cubed still in development?",
        "Cubed Twah~",
        "Remember when I used to beat your ass over the creamed corn?",
        "No tweakers!",
        "We want you to be the cube..",
        "Your diggin in me!",
        "I couldn't even code to this, I seg faulted immediately! Clean up aisle my codebase!",
        "Thug hunteru no booru!",
        "We love lain..",
        "We love newgrounds..",
        "Featuring Dante",
        "Featuring Caliban",
        "Featuring Telesto",
        "They should have got the yogscast for the minecraft movie",
        "\"Do YU RRELY Tink PHI iS Relly a persn?\"",
        "More subtle gay scenes, than the Minecraft movie",
        "Secretly a Cubed Yaoi fanfiction",
        "Proompterss.. Paradise.",
        "We like the yap sheesh.",
        "Your not on the hi list!",
        "KEVIN!",
        "Damit kevin",
        "If you think this a political thing, your missing the point",
        "Goodbye, to the GR8 D2P@1R",
        "It will be out when its out",
        "We make the homies say ho! and the girlies wanna scream!",
        "RFK Jr. put me on the autism registery... :<",
        "Someone quickly commisison Animan Studios for a cubed phi trailer!",
        "If you give me 10,000 american, I will make a 20 hour unskippable gay sex scene with Caliban and Dante",
        "20 dollars is 20 dollars",
        "If you read this, you are a loser.",
        "If you read this, you get the joke.",
        "Cubed-phi tuah~",
        "Unit test that thang!",
        "Fumo fumo fumo fumo fumo fumo fumo fumo fumo fumo fumo fumo fumo fumo",
        "Cirno will be in the game eventually.",
        "Koishi will be in the game eventually.",
        "Satori will be in the game eventually.",
        "Reimu will be in the game eventually.",
        "This ain't shit nothing to me man.",
        "If read this, then you know",
        "I need my autism samplier platter.",
        "Teto <<< Miku",
        "Watch vivianevixen Steam on twitch!",
        "Play Touhou.",
        "Watch KKHTA",
        "Watch Nixonverse",
        "Caliban is the best character.",
        "Dante is the best character.",
        "Telesto is the best character.",
        "FOR THE LOVE OF GOD, PLEASE STOP!",
        "FOR THE LOVE OF GOD, CALIBAN IS NOT A SELF INSERT!",
        "Would it be werid, if I told you caliban was based off my miscarried brother?",
        "Would it be werid, if I told you that some of the characters are based off people I've met?",
        "Would it be werid, if I told you that some of the characters are based off people I've met and hated?",
        "Its the Party of your lifetime.",
        "Under the neon glow..",
        "Packet, Would. Zeke, Absolutely. The others probably not.",
        "Neon Lights flicker, and DJ spins the track.",
        "The signal strong, can you feel it? In the floor?",
        "Somthing big is coming, but its just the beginning.",
        "We are not related to the techrot",
        "This obsession has turned, Into the great despair.",
        "NaN", 
        "GR8 D2P@1R",
    };
    public static string GetSplashText() => Splashtext[UnityEngine.Random.Range(0, Splashtext.Length)];
    public static string GetCurrentSplash() => CurrentSplash;
    public static string CurrentSplash = Splashtext[UnityEngine.Random.Range(0, Splashtext.Length)];
}
